# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moa < Formula
  desc "Self-hosted coding agent you can steer from anywhere"
  homepage "https://letmoa.run"
  version "0.24.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.24.0/moa_0.24.0_darwin_amd64.tar.gz"
      sha256 "75eb88edc1a107b6071bdf69460ab2fdce5576dfce5aceb8473c5bb6010d6060"

      define_method(:install) do
        bin.install "moa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.24.0/moa_0.24.0_darwin_arm64.tar.gz"
      sha256 "759de05ff8b3a257b24dbb149a631961c2881f63225d65756a88076584a06229"

      define_method(:install) do
        bin.install "moa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.24.0/moa_0.24.0_linux_amd64.tar.gz"
      sha256 "3409b24d091ee4329ebf273f6686898a882c7fab9f173eadc37e514a05f35bb7"
      define_method(:install) do
        bin.install "moa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.24.0/moa_0.24.0_linux_arm64.tar.gz"
      sha256 "ef202b6b8f36fabeca25f0677289b779277de08a851ed8b9ff37aff6d761cb4c"
      define_method(:install) do
        bin.install "moa"
      end
    end
  end

  test do
    system "#{bin}/moa", "version"
  end
end
