# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moa < Formula
  desc "Self-hosted coding agent you can steer from anywhere"
  homepage "https://letmoa.run"
  version "0.36.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.36.0/moa_0.36.0_darwin_amd64.tar.gz"
      sha256 "ec94674def7841aeae24b52650324f56fb2421e74706507e6713416dad53ba24"

      define_method(:install) do
        bin.install "moa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.36.0/moa_0.36.0_darwin_arm64.tar.gz"
      sha256 "a225c881917821d1a31107ddeba9c521be8f2a94ecba20219f9dc1661f2af2ae"

      define_method(:install) do
        bin.install "moa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.36.0/moa_0.36.0_linux_amd64.tar.gz"
      sha256 "e2b3baeda108484c8f1732ae301b7b182c02c956aefe639e7ad996d69b4435fc"
      define_method(:install) do
        bin.install "moa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/e-aleixandre/moa/releases/download/v0.36.0/moa_0.36.0_linux_arm64.tar.gz"
      sha256 "32d39228d4503631299ab5263d123c12d689240742c089a20abaecc4a8c8a73f"
      define_method(:install) do
        bin.install "moa"
      end
    end
  end

  test do
    system "#{bin}/moa", "version"
  end
end
